# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre y apellido')),
                ('correo', models.CharField(max_length=150, verbose_name='Correo el\xe9ctronico')),
                ('texto', models.TextField(verbose_name='Texto')),
            ],
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del lugar')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direcci\xf3n')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='Lugares/')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitud')),
                ('lng', models.CharField(max_length=50, verbose_name='Longitud')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
