# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 14:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comite', models.CharField(max_length=300, verbose_name='Comite')),
            ],
        ),
        migrations.CreateModel(
            name='comiteElectoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('cedula', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Cedula')),
                ('foto', models.FileField(blank=True, null=True, upload_to='fotosComites')),
                ('direccion', models.CharField(max_length=300, verbose_name='Direccion')),
                ('correo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='condicionHabitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=25, verbose_name='Condici\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Designacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig', models.CharField(max_length=50, verbose_name='Designacion')),
            ],
        ),
        migrations.CreateModel(
            name='Dincapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad', models.CharField(max_length=300, verbose_name='Dincapacidad')),
            ],
        ),
        migrations.CreateModel(
            name='estadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=50, verbose_name='Estado civil')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.CharField(max_length=9, verbose_name='Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('cedula', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='C\xe9dula')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=300, verbose_name='Direcci\xf3n')),
                ('num_casa', models.CharField(blank=True, max_length=15, verbose_name='N\xb0 de casa')),
                ('telf_cel', models.IntegerField(blank=True, null=True, verbose_name='Telf celular')),
                ('telf_hab', models.IntegerField(blank=True, null=True, verbose_name='Telf de habitaci\xf3n')),
                ('telf_ofic', models.IntegerField(blank=True, null=True, verbose_name='Telf de oficina')),
                ('correo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo el\xe9ctronico')),
                ('manzana', models.IntegerField(verbose_name='M\xe1nzana')),
                ('trabaja', models.CharField(blank=True, max_length=2, null=True, verbose_name='Trabaja?')),
                ('ingreso_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Ingreso mensual')),
                ('cne', models.CharField(blank=True, max_length=2, verbose_name='Inscrito en CNE?')),
                ('embarazo', models.CharField(blank=True, max_length=2, verbose_name='Embarazo precoz?')),
                ('status', models.BooleanField(default=True)),
                ('condicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.condicionHabitante')),
                ('discapacidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Dincapacidad')),
                ('estado_civil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.estadoCivil')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Incapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incapacidad', models.CharField(max_length=300, verbose_name='Incapacidad')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=25, verbose_name='Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='nivelInstruccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_instruccion', models.CharField(max_length=300, verbose_name='Nivel de instrucci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre de la p\xe1gina')),
            ],
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension', models.CharField(max_length=300, verbose_name='Pension')),
            ],
        ),
        migrations.CreateModel(
            name='profesionOficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion_oficio', models.CharField(max_length=300, verbose_name='Profesi\xf3n / Oficio')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='T\xedtulo')),
                ('descripcion', models.TextField(verbose_name='Descrici\xf3n')),
                ('imagen', models.FileField(upload_to='Publicaciones', verbose_name='Imag\xe9n')),
                ('url_album', models.CharField(max_length=300, verbose_name='Link de album en facebook')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Vocero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('cedula', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Cedula')),
                ('foto', models.FileField(blank=True, null=True, upload_to='fotosVoceros')),
                ('direccion', models.CharField(max_length=300, verbose_name='Direccion')),
                ('correo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono')),
                ('votos', models.IntegerField(verbose_name='Votos obtenidos')),
                ('status', models.BooleanField(default=True)),
                ('comite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Comite')),
                ('designacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Designacion')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Genero')),
            ],
        ),
        migrations.AddField(
            model_name='habitante',
            name='incapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Incapacidad'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Nacionalidad'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='nivel_instruccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.nivelInstruccion'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='pension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Pension'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='profesion_oficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.profesionOficio'),
        ),
        migrations.AddField(
            model_name='comiteelectoral',
            name='designacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Designacion'),
        ),
        migrations.AddField(
            model_name='comiteelectoral',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Genero'),
        ),
    ]
