# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2011-03-03 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20160514_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=40, verbose_name='T\xedtulo'),
        ),
    ]
