# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2011-03-04 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20110303_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=60, verbose_name='T\xedtulo'),
        ),
    ]
